### ISSUE TITLE
Active edge not activated: Android 12 / Pixel 4

### ISSUE THREAD

**Issue by LoicMahieu** [obynio/elmyra#2]
Hey,

Thanks for sharing this project.
I installed it in my Pixel 4 running with Android 12.
I can select Elmyra as assistant in settings but after that, active edge seems completely disabled.

Do you have any idea ?

I am looking in doc but I am not an android dev, being quite lost ;)

Thanks

**Comment by obynio** [comment]
> [..] but I am not an android dev

Me neither x)

I suppose Google changed **again** their Active Edge API in Android 12 which breaks Elmyra...
I'm afraid I can't do much since my own Pixel 4 Active Edge is broken due to a water leak, sorry :(

**Comment by LoicMahieu** [comment]
> I'm afraid I can't do much since my own Pixel 4 Active Edge is broken due to a water leak, sorry :(

Ha damn physically broken you think ?

> Me neither x)

I see work at Algolia. Amazing service ;)
Can't figure it out how it can so blazing fast!

Anyway, it's not the subject.
I'll take another look to the document when I'll have time.
Native google assistant have a settings which enable or not the active edge.
Maybe Elmyra shoud trigger some obscure api to specifically enable it...

I'll update this post if I find something.
Thanks!
